/* Questão 1A */

SELECT DISTINCT P.NOME, P.ESTADO, V.ANO_FABRICACAO
FROM PROPRIETARIO P 
INNER JOIN VEICULO V ON P.COD_PROPRIETARIO = V.COD_PROPRIETARIO
WHERE V.ANO_FABRICACAO IN (1990, 1996, 1998);

/* Questão 1B */

SELECT DISTINCT NOME, ESTADO
FROM PROPRIETARIO
WHERE COD_PROPRIETARIO IN (
    SELECT COD_PROPRIETARIO 
    FROM VEICULO 
    WHERE ANO_FABRICACAO IN (1990, 1996, 1998)
);

/* Questão 2A */

SELECT V.PLACA, V.MODELO
FROM VEICULO V 
INNER JOIN PROPRIETARIO P ON V.COD_PROPRIETARIO = P.COD_PROPRIETARIO
WHERE P.CIDADE IN ('Belo Horizonte', 'Rio de Janeiro');

/* Questão 2B */

SELECT PLACA, MODELO
FROM VEICULO
WHERE COD_PROPRIETARIO IN (
    SELECT COD_PROPRIETARIO
    FROM PROPRIETARIO
    WHERE CIDADE IN ('Belo Horizonte', 'Rio de Janeiro')
);

/* Questão 3A */

SELECT DISTINCT P.NOME
FROM PROPRIETARIO P 
INNER JOIN VEICULO V ON P.COD_PROPRIETARIO = V.COD_PROPRIETARIO
WHERE V.VALOR_IPVA BETWEEN 200 AND 600;

/* Questão 3B */

SELECT DISTINCT NOME
FROM PROPRIETARIO
WHERE COD_PROPRIETARIO IN (
    SELECT COD_PROPRIETARIO
    FROM VEICULO
    WHERE VALOR_IPVA BETWEEN 200 AND 600
);

/* Questão 4 */

SELECT V.PLACA, V.MODELO
FROM VEICULO V
JOIN PROPRIETARIO P ON V.COD_PROPRIETARIO = P.COD_PROPRIETARIO
WHERE P.ESTADO = 'MG'
AND V.VALOR_IPVA < (
    SELECT AVG(V2.VALOR_IPVA)
    FROM VEICULO V2
    JOIN PROPRIETARIO P2 ON V2.COD_PROPRIETARIO = P2.COD_PROPRIETARIO
    WHERE P2.ESTADO = 'SP'
);

/* Questão 5 */

SELECT COD_PROPRIETARIO, MODELO, VALOR_IPVA, PLACA
FROM VEICULO V
WHERE VALOR_IPVA = (
    SELECT MAX(V1.VALOR_IPVA)
    FROM VEICULO V1
    WHERE V1.COD_PROPRIETARIO = V.COD_PROPRIETARIO
)
ORDER BY COD_PROPRIETARIO;

/* Questão 6 */

SELECT ANO_FABRICACAO, VALOR_IPVA, PLACA
FROM VEICULO V
WHERE VALOR_IPVA = (
    SELECT MIN(V1.VALOR_IPVA)
    FROM VEICULO V1
    WHERE V1.ANO_FABRICACAO = V.ANO_FABRICACAO
)
ORDER BY ANO_FABRICACAO;

/* Questão 7 */

SELECT P.CIDADE, P.ESTADO, V.PLACA, V.MODELO, V.ANO_FABRICACAO
FROM VEICULO V 
INNER JOIN PROPRIETARIO P ON V.COD_PROPRIETARIO = P.COD_PROPRIETARIO
WHERE V.ANO_FABRICACAO = (
    SELECT MIN(V1.ANO_FABRICACAO)
    FROM VEICULO V1 
    INNER JOIN PROPRIETARIO P1 ON V1.COD_PROPRIETARIO = P1.COD_PROPRIETARIO
    WHERE P1.CIDADE = P.CIDADE
)
ORDER BY P.ESTADO, P.CIDADE;

/* Questão 8 */

SELECT V.PLACA, V.MODELO, V.VALOR_IPVA
FROM VEICULO V
JOIN PROPRIETARIO P ON V.COD_PROPRIETARIO = P.COD_PROPRIETARIO
WHERE V.VALOR_IPVA > (
    SELECT AVG(V2.VALOR_IPVA)
    FROM VEICULO V2
    JOIN PROPRIETARIO P2 ON V2.COD_PROPRIETARIO = P2.COD_PROPRIETARIO
    WHERE P2.ESTADO = P.ESTADO
);
