/* Questão 1 */

SELECT PLACA AS Placa, MODELO AS Modelo
FROM VEICULO
WHERE MODELO LIKE 'FIAT%';

/* Questão 2 */

SELECT ESTADO AS Estado, NOME AS "Nome do Proprietário"
FROM PROPRIETARIO
WHERE ESTADO IN ('MG', 'RJ', 'SP', 'PR', 'CE')
ORDER BY ESTADO, NOME;

/* Questão 3 */

SELECT *
FROM VEICULO
WHERE VALOR_IPVA IS NULL
ORDER BY PLACA;

/* Questão 4 */

SELECT PLACA AS Placa, MODELO AS Modelo
FROM VEICULO
WHERE ANO_FABRICACAO <> 1996 
AND VALOR_IPVA BETWEEN 150 AND 200
ORDER BY PLACA;

/* Questão 5 */

SELECT *
FROM PROPRIETARIO
WHERE CIDADE = 'Belo Horizonte';

/* Questão 6 */

SELECT PLACA AS Placa, ANO_FABRICACAO AS "Ano de Fabricação"
FROM VEICULO
WHERE PLACA LIKE 'G__-__75';

/* Questão 7 */

SELECT PLACA AS Placa, MODELO AS Modelo, VALOR_IPVA AS IPVA
FROM VEICULO
WHERE ANO_FABRICACAO IN (1988, 1990, 1996, 1997) 
AND MODELO LIKE 'FORD%'
AND (VALOR_IPVA < 200 OR VALOR_IPVA > 800);

/* Questão 8 */

SELECT MODELO AS Modelo, VALOR_IPVA AS IPVA
FROM VEICULO
WHERE MODELO LIKE 'FIAT%' 
AND VALOR_IPVA BETWEEN 100 AND 800;

/* Questão 9 */

INSERT INTO PROPRIETARIO (COD_PROPRIETARIO, NOME, CIDADE, ESTADO) VALUES 
(1234, 'PESSOA 1', 'Belo Horizonte', 'MG'),
(2234, 'PESSOA 2', 'Belo Horizonte', 'MG'),
(3234, 'PESSOA 3', 'Belo Horizonte', 'MG'),
(4234, 'PESSOA 4', 'Belo Horizonte', 'MG'),
(5234, 'PESSOA 5', 'Belo Horizonte', 'MG'),
(6234, 'PESSOA 6', 'Belo Horizonte', 'MG'),
(7234, 'PESSOA 7', 'Belo Horizonte', 'MG');

INSERT INTO VEICULO (PLACA, MODELO, ANO_FABRICACAO, VALOR_IPVA, COD_PROPRIETARIO) 
VALUES ('FE2-8I43', 'MOBI', 2022, NULL, 1234);

/* Questão 10 */

UPDATE VEICULO
SET VALOR_IPVA = 200
WHERE PLACA = 'FE2-8I43';
