/* Questão 1 */

SELECT P.NOME AS "Nome do Proprietário", V.MODELO AS Modelo
FROM VEICULO V
INNER JOIN PROPRIETARIO P ON V.COD_PROPRIETARIO = P.COD_PROPRIETARIO
WHERE P.ESTADO = 'MG'
ORDER BY P.NOME, V.MODELO;

/* Questão 2 */

SELECT P.ESTADO AS Estado, V.PLACA AS Placa, V.MODELO AS Modelo, 
       V.VALOR_IPVA AS "Valor do IPVA", P.NOME AS "Nome do Proprietário"
FROM VEICULO V
INNER JOIN PROPRIETARIO P ON V.COD_PROPRIETARIO = P.COD_PROPRIETARIO
WHERE P.ESTADO IN ('MG', 'RJ', 'SP') 
AND V.VALOR_IPVA BETWEEN 150 AND 350
ORDER BY P.ESTADO, V.PLACA;

/* Questão 3 */

SELECT P.NOME AS "Nome do Proprietário", V.PLACA AS Placa
FROM PROPRIETARIO P
LEFT JOIN VEICULO V ON P.COD_PROPRIETARIO = V.COD_PROPRIETARIO
ORDER BY P.NOME, V.PLACA;

/* Questão 4 */

SELECT P.NOME AS "Nome do Proprietário", V.PLACA AS Placa
FROM PROPRIETARIO P
LEFT JOIN VEICULO V ON P.COD_PROPRIETARIO = V.COD_PROPRIETARIO
UNION
SELECT NULL AS "Nome do Proprietário", V.PLACA AS Placa
FROM VEICULO V
WHERE V.COD_PROPRIETARIO IS NULL
ORDER BY "Nome do Proprietário", Placa;

/* Questão 5 */

SELECT P.ESTADO AS Estado, COUNT(V.PLACA) AS "Quantidade de Veículos"
FROM PROPRIETARIO P
JOIN VEICULO V ON P.COD_PROPRIETARIO = V.COD_PROPRIETARIO
GROUP BY P.ESTADO
HAVING COUNT(V.PLACA) > 4
ORDER BY P.ESTADO;

/* Questão 6 */

SELECT P.CIDADE AS Cidade, SUM(V.VALOR_IPVA) AS "Total IPVA Arrecadado"
FROM PROPRIETARIO P
JOIN VEICULO V ON P.COD_PROPRIETARIO = P.COD_PROPRIETARIO
GROUP BY P.CIDADE
ORDER BY SUM(V.VALOR_IPVA) DESC;

/* Questão 7 */

SELECT P.ESTADO AS Estado, COUNT(DISTINCT V.MODELO) AS "Quantidade de Modelos"
FROM PROPRIETARIO P
JOIN VEICULO V ON P.COD_PROPRIETARIO = V.COD_PROPRIETARIO
GROUP BY P.ESTADO
ORDER BY P.ESTADO;

/* Questão 8 */

SELECT P.NOME AS "Nome do Proprietário", COUNT(V.PLACA) AS "Quantidade de Veículos"
FROM PROPRIETARIO P
JOIN VEICULO V ON P.COD_PROPRIETARIO = V.COD_PROPRIETARIO
GROUP BY P.NOME
HAVING COUNT(V.PLACA) > 1
ORDER BY COUNT(V.PLACA) DESC;

/* Questão 9 */

SELECT V.MODELO AS Modelo, SUM(V.VALOR_IPVA) AS "Total IPVA"
FROM VEICULO V
WHERE V.MODELO LIKE 'FIAT%'
GROUP BY V.MODELO
ORDER BY SUM(V.VALOR_IPVA) DESC;

/* Questão 10 */

SELECT AVG(V.VALOR_IPVA) AS "Média do IPVA em SP"
FROM VEICULO V
JOIN PROPRIETARIO P ON V.COD_PROPRIETARIO = P.COD_PROPRIETARIO
WHERE P.ESTADO = 'SP';
